blogDemo/urls.py
from django.conf.urls import url,include
from django.contrib import admin

from sblog import urls as sblog_urls
from django_comments import urls as comments_urls

admin.autodiscover()

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^sblog/', include(sblog_urls,namespace= "sblog")),
    url(r'^comments/',include(comments_urls)),
]

sblog/urls.py
from django.conf.urls import url
from django.contrib import admin

from sblog import views as sblog_views
from django.views.generic import FormView
from .forms import BlogForm

admin.autodiscover()

urlpatterns = [
    url(r'^bloglist/',sblog_views.blog_list,name='bloglist'),
    url(r'^blog/(?P<id>\d+)/$',sblog_views.blog_show,name = "detailblog"),
    url(r'^blog/(?P<id>\w+)/del/$',sblog_views.blog_del,name="delblog"),
    url(r'^blog/tag/(?P<id>\d+)/$',sblog_views.blog_filter,name="filterblog"),
    url(r'^blog/add/$',sblog_views.blog_add,name="addblog"),
    url(r'^blog/(?P<id>\w+)/update/$',sblog_views.blog_update,name="updateblog"),
]

sblog/models.py
#coding:utf-8
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class Tag(models.Model):
    """docstring for Tags"""
    tag_name = models.CharField(u'标签',max_length=100,blank=True)
    create_time = models.DateTimeField(u'创建时间',auto_now_add=True)

   # def __unicode__(self):
   #     return  self.tag_name

    def __str__(self):
        return self.tag_name

class Author(models.Model):
    """docstring for Author"""
    name = models.CharField(u'姓名',max_length=30)
    email = models.EmailField(u'电子邮箱',blank=True)
    website = models.URLField(u'网址',blank=True)

   # def __unicode__(self):
   #     return self.name

    def __str__(self):
        return self.name

class Blog(models.Model):
    """docstring for Blogs"""
    caption = models.CharField(u'标题',max_length=50)
    author = models.ForeignKey(Author,verbose_name=u"作者")
    tags = models.ManyToManyField(Tag,blank=True,verbose_name=u'标签')
    content = models.TextField(u'内容')
    publish_time = models.DateTimeField(u'发布时间',auto_now_add=True)
    update_time = models.DateTimeField(u'更新时间',auto_now=True)

   # def __unicode__(self):
   #     return u'%s %s %s %s' % (self.caption,self.author,self.publish_time,self.tags)

    def tags_names(self):
        return ','.join([a.tag_name for a in self.tags.all()])

sblog/forms.py
#coding:utf-8
from django import forms
from pagedown.widgets import PagedownWidget
from .models import Blog,Tag,Author

class BlogForm(forms.ModelForm):
    caption = forms.CharField(
        required=True,
        widget=PagedownWidget(),
        error_messages={'required':'标题不能为空'},
        label=u'标题',
    )
    content = forms.CharField(
        required=True,
        widget=PagedownWidget(),
        error_messages={'required':'内容不能为空'},
        label=u'内容',
    )
    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.order_by('id'),
        required=True,
        error_messages={'required':u'至少选择一个'},
        widget=forms.CheckboxSelectMultiple,
        label=u'标签',
    )
    author = forms.ModelChoiceField(
        queryset=Author.objects.order_by('name'),
        required=True,
        error_messages={'required':u'请选择一个'},
        label=u'作者',
    )

    class Meta:
        model = Blog
        fields = '__all__'

    def save(self, inblog, commit=True):
        if inblog:
            blog = inblog
        else:
            blog = Blog()
        blog.caption = self.cleaned_data['caption']
        blog.content = self.cleaned_data['content']
        blog.author = self.cleaned_data['author']
        blog.author.save()
        tags = list(self.cleaned_data['tags'])
        blog.save()
        for item in tags:
            blog.tags.add(item)
        if commit:
            blog.save()
        return blog
"""
class TagForm(forms.ModelForm):
    tag_name = forms.CharField(widget=PagedownWidget())

    class Meta:
        model = Tag
        fields = '__all__'

class AuthorForm(forms.ModelForm):
    name = forms.CharField()

    class Meta:
        model = Author
        fields = '__all__'
"""

sblog/views.py
from django.shortcuts import render,redirect
from django.http import Http404

from .models import Blog,Tag,Author
from .forms import BlogForm

# Create your views here.

def blog_list(request):
    blogs = Blog.objects.all()
    tags = Tag.objects.all()
    return render(request,"sblog/blog_list.html",{"blogs":blogs,"tags":tags})

def blog_show(request,id):
    try:
        blog = Blog.objects.get(id = id)
    except Blog.DoesNotExist:
        raise Http404
    return render(request,"sblog/blog_show.html",{"blog":blog})

def blog_del(request,id=""):
    try:
        blog = Blog.objects.get(id=id)
    except Exception:
        raise Http404
    if blog:
        blog.delete()
        return  redirect("/sblog/bloglist/")
    blogs = Blog.objects.all()
    return render(request,"sblog/blog_list.html", {"blogs": blogs})

def blog_filter(request,id=""):
    tags = Tag.objects.all()
    tag = Tag.objects.get(id = id)
    blogs = tag.blog_set.all()
    return  render(request,"sblog/blog_list.html", {"blogs": blogs, "tags": tags})

def blog_add(request):
    if request.method == "POST":
        form = BlogForm(request.POST)
       # tag = TagForm(request.POST)
       # author = AuthorForm(request.POST)

        if form.is_valid():
            form.save()
           # cdTag = tag.cleaned_data
           # cdAuthor = author.cleaned_data
           # tagname = cdTag['tag_name']
           # for taglist in tagname.split():
           #     Tag.objects.get_or_create(tag_name = taglist.strip())

           # author = Author.objects.get_or_create(name=cdBlog['author'])

           # tags = Tag.objects.get_or_create(tag_name=cdBlog['tags'])
           # blog = Blog(caption=title,author=cdBlog['author'],content=content,tags=cdBlog['tags'])
           # for taglist in taglist.split():
           #     blog.tags.add(Tag.objects.get(tag_name=taglist.strip()))
           # blog.save()
            id = Blog.objects.order_by('-publish_time')[0].id
            try:
                print(BlogForm.__dict__)
            except Exception as ex:
                print(ex)
            return redirect("/sblog/blog/%s" % id)
        else:
            print(form.is_valid())
           # print(tag.is_valid())
    else:
        form = BlogForm()
       # tag = TagForm(initial={'tag_name':'notags'})
       # author = AuthorForm(initial={'name':'noname'})
    return render(request,"sblog/blog_add.html",{'form':form})

def blog_update(request,id=""):
    id=id
    blog = Blog.objects.get(id=id)
    if request.method == "POST":
        form = BlogForm(request.POST)
       # tag = TagForm(request.POST)
        if form.is_valid():
            form.save(blog)

            """
            cd = form.cleaned_data
            cdtag = tag.cleaned_data
            tagname = cdtag['tag_name']
            tagnamelist = tagname.split()
            for tag in tagnamelist:
                Tag.objects.get_or_create(tag_name=tag.strip())
            title = cd['caption']
            content = cd['content']

            if blog:
                blog.caption = title
                blog.content = content

                blog.save()
                for tag in tagnamelist:
                    blog.tags.add(Tag.objects.get(tag_name=tag.strip()))
                    blog.save()
                tags = blog.tags.all()
                for tag in tags:
                    tag = str(tag)
                    if tag not in tagnamelist:
                        notag = blog.tags.get(tag_name=tag)
                        blog.tags.remove(notag)

            else:
                blog = Blog(caption=title,content=content)
               # for tag in tagnamelist:
               #     blog.tags.add(Tag.objects.get(tag_name=tag.strip()))
                blog.save()
            """
            return redirect('/sblog/blog/%s' % id)
        else:
            print(form.is_valid())
    else:
        try:
            blog = Blog.objects.get(id=id)
        except Exception:
            raise Http404
        form = BlogForm(initial={'caption':blog.caption,'content':blog.content})
        """tags = blog.tags.all()
        if tags:
            taginit = ""
            for x in tags:
                taginit += str(x)+' '
            tag = TagForm(initial={'tag_name':taginit})
        else:
            tag = TagForm()
        """
    return render(request,"sblog/blog_add.html",{'blog':blog,'form':form})

mycomments/templates/comments/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

sblog/templates/comments/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% comment %}

{% endcomment %}

</body>
</html>

sblog/templates/comments/sblog/form.html
<!DOCTYPE html>
<!-- Comments Form-->
{% load comments i18n crispy_forms_tags %}

<div id="wrap-form-comment">
    <div class="well row" id="form-comment">
        <div class="col-lg-12 col-md-12">
            <h4>Leave a Comment:</h4>
            <form role="form" action="{% comment_form_target %}" method="post">
                {% csrf_token %}
                {% if next %}
                    <div><input type="hidden" name="next" value="{{ next }}"/></div>
                {% endif %}
                {{ form|crispy }}
                <button type="submit" class=" btn btn-primary btn-lg col-lg-offset-4">Submit</button>
                <button id="cancel_reply" type="button" class="btn btn-lg btn-info col-lg-offset-1">Cancel Reply</button>
            </form>
        </div>
    </div>
</div>

sblog/templates/comments/sblog/list.html
<!DOCTYPE html>
{% load threadedcomments_tags %}
{% load custom_markdown %}

<div class="comments_length">
    <p>{{ comment_list|length }} Comments</p>
</div>

<div class="comments">
    {% for comment in comment_list|fill_tree|annotate_tree %}
        {% if comment.open %}
            <ul>
        {% else %}
			</li>
        {% endif %}
        <li class="comment_li" id="c{{ comment.id }}">
            <div class="comment">
                <div class="comment_info">
                    <div class="comment_user"><i class="glyphicon glyphicon-user"></i> {{ comment.user_name }}</div>
					<div class="comment_data">
						<i class="glyphicon glyphicon-time"></i> {{ comment.submit_date|date:"d M Y, H:i" }}
						| <a href="#c{{ comment.id }}" data-comment-id="{{ comment.id }}" class="comment_reply_link">Reply</a>
					</div>
                </div>
                <div class="comment_text">
					{{ comment.comment|custom_markdown }}
				</div>
			</div>
			{% for close in comment.close %}
				</li></ul>
			{% endfor %}
    {% endfor %}
</div>

sblog/templates/sblog/base.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>
		{% block title %}
		{% endblock %}
	</title>
    <meta name="viewport" content="width=dvice-width,initial-scale=1">
    {% load static %}
    {% load staticfiles %}
    {{ form.media }}
    <link  href="/static/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="/static/css/mycomments.css">
    <script src="/static/js/jquery.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    <script src="/static/js/myJS.js"></script>
    <link rel="stylesheet" href="http://yandex.st/highlightjs/8.0/styles/rainbow.min.css">
    <script src="http://yandex.st/highlightjs/8.0/highlight.min.js"></script>
    <script>hljs.initHighlightingOnLoad();</script>

</head>

<body>
	{% block body %}
	    {% block header %}
            {# r任何一个页面都可以修改的文本区域 #}
            {% block menu %}
            {# 菜单(导航栏)应该包含在这个区域中,它是针对站点级的导航,不是每个页面专属的导航菜单 #}
            {% endblock %}
        {% endblock %}

        {% block content %}
            {# 这个区块用来放置页面正文内容,任何页面正文内容都可能不一样,它不包含任何站点导航,信息头,页脚,或其它任何属于base模版的东东 #}
            <div class="container">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-9 col-lg-9">
                            {% block article %}
                                {% block article_title %}
                                    {% comment %}
                                    用来指定 content 区块的 "title". 比如 blog 的标题.
                                也可以用来 包含 content 内的导航 (译注: 比如提纲), 或其它类似的东东.
                                大致都是些 页面中并非主要内容的东东.
                                我不知道这个区块是否应该放到 content tag 内, 并且对应于前面建议的 content tag,
                                是不是还需要一个 main_content 区块.
                                {% block [section]_menu %} {% block page_menu %}
                                这是对应于之前建议的 menu 区块. 用来导航一个章节或页面.
                                    {% endcomment %}
                                {% endblock %}
                                {% block article_content %}{% endblock %}
                            {% endblock %}

                            {% block article_menu %}{% endblock %}
                            {% block mycomments %}{% endblock %}
                        </div>
                        <div class="col-md-3 col-lg-3">
                            {% block aside %}
                                {% block tags %}{% endblock %}
                            {% endblock %}
                        </div>
                    </div>
                </div>
            </div>
        {% endblock %}
        {% block footer %}
            {# 任何一个页面都可能修改的文本区域的页脚 #}
            <p>Thanks for visiting my site!</p>
        {% endblock %}
    {% endblock %}

</body>
</html>

sblog/templates/sblog/blog_add.html
<!DOCTYPE html>
{% extends "sblog/blog_base.html" %}
{% block title %} 发布文字 {% endblock %}

{% block content %}
    {% block article %}
        <form action="" method="post" >
            {% csrf_token %}
            {% for field in form %}
                <div class="form-group row">
                    <div class="col-md-2 col-lg-1 col-lg-offset-1">
                        <h4>{{ field.label_tag }}</h4>
                    </div>
                    <div class="col-md-2 col-lg-2">
                        {{ field }}<span style="color: red;">{{ field.errors }}</span>
                    </div>
                </div>
            {% endfor %}

            {% comment 用于判断form.is_valid()为False的原因 %}
            {% for field in form %}
                <div class="fieldWrapper">
                    {{ field.errors }}
                    {{ field.label_tag }} {{ field }}
                </div>
            {% endfor %}
            {% endcomment %}
            <div class="col-lg-offset-2">
                <input class="btn btn-primary" type="submit" value="Save&Add">
            </div>
        </form>
    {% endblock %}
{% endblock %}

sblog/templates/sblog/blog_base.html
<!DOCTYPE html>
{% extends "sblog/base.html" %}

{% block extra_head %}
    <style>
        body{
            padding-top: 60px;
        }
    </style>
{% endblock %}

{% block header %}
    {% block menu %}
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a class="navbar-brand" href="#">BLOGS</a>
                </div>
                <div>
                    <ul class="nav navbar-nav">
                        <li class="active ">
                            <a href="{% url 'sblog:bloglist' %}">home</a>
                        </li>
                        <li>
                            <a href="#">about</a>
                        </li>
                        <li>
                            <a href="#">contact</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    {% endblock %}
{% endblock %}

sblog/templates/sblog/blog_filter.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

sblog/templates/sblog/blog_list.html
<!doctype html>
{% extends "sblog/blog_base.html" %}
{% load threadedcomments_tags %}

{% block title %} blog list {% endblock %}

{% block article %}
<article class="container-fluid" >
    {% for blog in blogs %}
        <p class="text-muted">
            {% for tag in blog.tags.all %}
                <span style="background-color: #66afe9;padding: 3px;color: #dd1144;border-radius: 5px;"><i class="glyphicon glyphicon-tag"></i><small>{{ tag.tag_name }}</small></span>
            {% endfor %}
        </p>
        {% load custom_markdown %}
        <h2 class="text-center"><a href="{% url 'sblog:detailblog' blog.id %}">{{ blog.caption }}</a></h2>
        <div class="row">
            <div class="col-md-6 col-lg-6">
                <h3>作者:{{ blog.author.name }}</h3>
            </div>
            <div class="col-md-6 col-lg-6">
                <h3 class="text-muted"><i class="glyphicon glyphicon-time"></i><small>发布时间:{{ blog.publish_time }}</small> </h3>
            </div>
        </div>

        <button class="btn btn-warning" onclick="toggle({{ blog.id }})">SHOW CONTENT</button>
        <div class="row" id="{{ blog.id }}" style="display: none;">
            <div class="col-lg-12">
                {{ blog.content|custom_markdown }}
            </div>
        </div>

        <div class="row">
            <div class="col-md-10 col-lg-10">
                <p class="text-muted"><i class="glyphicon glyphicon-time"></i><small>更新时间:{{ blog.update_time }}</small> </p>
            </div>
            <div class="col-md-2 col-lg-2">
                <a href="{% url 'sblog:updateblog' blog.id %}" title="edit"><i class="glyphicon glyphicon-edit"></i> </a>
                <a href="{% url 'sblog:delblog' blog.id %}" title="delete"><i class="glyphicon glyphicon-trash col-md-offset-1"></i></a>
                {% get_comment_count for blog as comment_count %}
                <a href="{% url 'sblog:detailblog' blog.id %}#cmt" title="comment"><i class="glyphicon glyphicon-comment col-md-offset-1"></i>{{ comment_count }} </a>
            </div>
        </div>
        <hr style="filter:alpha(opacity=100,finishopacity=0,style=2);width:100%;background-color:#ebcccc;height:5px" />
    {% endfor %}
</article>
{% endblock %}

{% block aside %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12 col-lg-12" style="position: relative;top: 50px;">
                <a class="btn-success btn-lg " style=" text-decoration: none" href="{% url 'sblog:addblog' %}">
                    <i class="icon-plus"></i>add new blog
                </a>
            </div>
            <div class="col-md-12 col-lg-12" style="position: relative;top: 100px">
                {% block tags %}
                <div class="well well-large">
                {% for tag in tags %}
                    <span class="label label-danger"><a style="color: #f9f9f9; font-size: 15px; padding: 2px" href="{% url 'sblog:filterblog' tag.id %}">{{ tag.tag_name }}</a></span>
                {% endfor %}
                <span class="label label-primary"><a style="color: #f9f9f9; font-size: 15px; padding: 2px" href="{% url 'sblog:bloglist' %}">ALL</a> </span>
                </div>
                {% endblock %}
            </div>
        </div>
    </div>
{% endblock %}

sblog/templates/sblog/blog_show.html
<!doctype html>
{% extends "sblog/blog_base.html" %}
{% block title %}{{blog.caption}}{% endblock %}

{% block content %}
    {% block article %}
    <div class="content">
        <article class="container-fluid">
            {% block article_title %}
                <h2 style="color: #dd1144;text-align: center;">{{ blog.caption }}</h2>
            {% endblock %}
            <div class="row text-muted">
                <div class="col-md-6 col-md-offset-2 col-lg-6 col-lg-offset-2">
                    <i class="glyphicon glyphicon-user"></i><small>作者:{{ blog.author.name }}</small>
                </div>
                <div class="col-md-4 col-lg-4">
                    <i class="glyphicon glyphicon-time " ></i><small>更新时间:{{ blog.update_time }}</small>
                </div>
            </div>

            <div class="container-fluid">
                {% block article_content %}
                    {% load custom_markdown %}
                    <div class="row">{{ blog.content|custom_markdown }}</div>
                {% endblock %}

                <div class="row">
                    <div class="col-md-10 col-lg-10">
                        <p>
                            {% for tag in blog.tags.all %}
                                <span style="background-color: #66afe9;padding: 3px;color: #dd1144;border-radius: 5px;"><i class="glyphicon glyphicon-tag"></i>
                                <small class="text-muted">{{ tag.tag_name }}</small></span>
                            {% endfor %}
                        </p>
                    </div>
                    <div class="col-md-2 col-lg-2">
                        <a href="{% url 'sblog:updateblog' blog.id %}" title="edit"><i class="glyphicon glyphicon-edit col-md-offset-1"></i> </a>
                        <a href="{% url 'sblog:delblog' blog.id %}" title="delete" ><i class="glyphicon glyphicon-trash col-md-offset-1"></i> </a>
                        {% load threadedcomments_tags %}
                        {% get_comment_count for blog as comment_count %}
                        <a href="#cmt" title="comment"><i class="glyphicon glyphicon-comment col-md-offset-1"></i>{{ comment_count }} </a>
                    </div>
                </div>
            </div>
        </article>
    </div>

    {% block mycomments %}
        <h2>Comments for {{ blog.caption }}:</h2>
        {% render_comment_list for blog %}   <!--这段代码有问题-->
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-10">
                    {% render_comment_form for blog %}
                </div>
            </div>
        </div>
    {% endblock %}

    {% endblock %}
{% endblock %}

{% block footer %}
    <i class="glyphicon glyphicon-time"></i><small>发布时间:{{ blog.publish_time }}</small>
{% endblock %}